### ISSUE TITLE
Prettier reformat adds unwanted whitespace to HTML

### ISSUE THREAD

**Issue by hidde** [sveltejs/prettier-plugin-svelte#103] opened 2020-06-24 08:15 UTC
Given the following HTML:

```html
<p>Please use <a href="https://en.wikipedia.org/wiki/Markdown">Markdown</a>, 
so that you can use lists, links and code examples.</p>
```

## Actual result

Formatted with `prettier-plugin-svelte`, my comma is moved to a new line, which introduces whitespace between the link and the comma: 

```html
<p>
   Please use
    <a href="https://en.wikipedia.org/wiki/Markdown">Markdown</a>
    , so that you can use lists, links and code examples.
</p>
``` 

It prints “Please use Markdown , so”.

## Desired result

I'm trying to avoid that whitespace before the comma.

When formatted with the `html` parser of Prettier, no whitespace is forced  ([REPL](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEQPIGEAqAmgAoCiABABYwC2ANgHwA6Uq195dAhlAOYC8TEAiHMo5CeTZwuAEzGTFUmnBhdyYSlwBOAZ1WCQAVXwAxALQAOIeQD0CpRNQq15KFxWGAbgEs4AdwAHCG0YG0hYBBhDfx9ZGEp+WThfMDhzWPjKABpyHygfGB8uOnNdMBK4fgBGADoABht7FkcnIpg6OAZMCDAAVxVYVFt2zocnW0oZeRbJVAAjCFkAT3GlVECGYk6ufXI+vdR1Sm04ADNDahhA3SRbWwRa2IBrH0C4WWLakN5bF59bABZHTPWQQfxQUTA7Sg8GsWxcBi5XQQcgJLgwcjLCB9DQ8fZ7Og+XQwXS5IlQZ66cg8WQaJZwchwAAeHkCnV0tWGm1mjg2Wx2ewOcG0UmOpwuQiuNzuDygTx8r3eny4320v3+QJBYIhUO1cOGiORqPRmOxuIq4mFnGJpPJ+SpNKgdMgySZrJo7LgnO5a0U-O2MiF+j0YqoEsuMGut3uj3+yq+Pz+ioB0NhupADDTOvhRvIKLRWjNOLxVsJtrJNsp1Np9LdLLZHK5th54jmtkWKzEw3YjBYIGyIAggSK0F0yFAOm04OIOgQ45QJX8XGW48H820XDAz1UAGVAlv8rxkDBtH04IPewB1SiFb0HtK7+eFHy+GDLZDgXRrkD5EMwYhN14GguGQM4Sn0QcACtdGZAAhTdtz3Dw4AAGXyOAwIgi8QBg5ldyPToAEU+ggeAsLoSCQAPPQRU-XsB2o7R8hgK84gSZBLHqQdAmnfQr03QJP1470RS8TDBwAR1I+BAOHBcQF2cwoDgD4PkY05pJ8U5AK4YDQKQcDKJw-QaB8E8zxMwi4BIsjMMM7DBzUeY2KyZAACYnM3HwKV4XAIBoEDP29ABWRjhXwLh5gXIyqK8c8AElnSiXcwGYkcAEFnV3d9Ogo-QAF8CqAA)).

Is `prettier-plugin-svelte` parsing this with something else than the `html` parser and would it be possible to change that?

**Comment by tiffany352** [comment] 2020-08-06 19:18
Prettier has a config option `"htmlWhitespaceSensitivity": "strict"` and it seems like it's completely ignored by this tool. I've been having a really hard time with this because it ends up mattering a lot in my case. I may need to stop using prettier entirely until there's a solution for this.

**Comment by tiffany352** [comment] 2020-08-06 21:34
I found out you can use `<!-- prettier-ignore -->` and it will be respected, which works well enough for me.

**Comment by ehrencrona** [comment] 2020-08-10 11:50
I created [a pull request](https://github.com/sveltejs/prettier-plugin-svelte/pull/116) that fixes this problem.

**Comment by ehrencrona** [comment] 2020-08-10 11:53
This is by the way a duplicate of #24

**Closed** 2020-08-27 10:30 UTC
