### ISSUE TITLE
Select and TextArea Carbon components get lower-cased

### ISSUE THREAD

**Issue by pjebs** [sveltejs/prettier-plugin-svelte#278] opened 2022-02-25 07:00 UTC
```
<script lang="ts">
	import {
		ComposedModal,
		ModalHeader,
		ModalBody,
		ModalFooter,
		Select,
		SelectItem,
		TextArea,
	} from 'carbon-components-svelte';

	export let open = false;
</script>

<ComposedModal bind:open="{open}" size="sm">
	<ModalHeader label="" title="X" />
	<ModalBody hasForm>
		<Select labelText="Carbon theme" selected="g10">
			<SelectItem value="white" text="White" />
			<SelectItem value="g10" text="Gray 10" />
			<SelectItem value="g80" text="Gray 80" />
			<SelectItem value="g90" text="Gray 90" />
			<SelectItem value="g100" text="Gray 100" />
		</Select>
		<TextArea required labelText="App description" placeholder="Enter a description..." />
	</ModalBody>
	<ModalFooter primaryButtonText="Confirm" />
</ComposedModal>

```

Prettier makes `TextArea` into `textarea` and `Select` into `select`

**Comment by dummdidumm** [comment] 2022-03-29 08:18
I cannot reproduce this. Please make sure to use the latest version of the plugin. If you do, please provide more info so it's reproducible.

**Comment by dummdidumm** [comment] 2022-09-26 14:46
No reproduction provided, closing

**Closed by dummdidumm** 2022-09-26 14:46 UTC
