### ISSUE TITLE
after select a word and press open curly braces "{" the entirely <script/> section is replace by  prettier:content="CiAgZXhwb3J0IGxldCBuYW1lOwo="

### ISSUE THREAD

**Issue by eriknyk** [sveltejs/prettier-plugin-svelte#413] opened 2023-12-13 17:36 UTC
Problem
---

After select a word and press open curly braces "{" then editor should close the curly brakets with "}" enclosing the selected workd, but a the entirely <script> section is replace by  prettier:content="CiAgZXhwb3J0IGxldCBuYW1lOwo=">{}

Behaviour Expected
---
It only enclose the selected word with curly brackets, from: `firstName` to: `{firstName}` only.

https://github.com/sveltejs/prettier-plugin-svelte/assets/205721/ce664f91-2c97-4d4e-a30e-b7c199c8121c

**Comment by dummdidumm** [comment] 2024-01-29 10:30
Closing as duplicate of #233 and #242
TLDR: prettier does not support plugin like prettier-plugin-svelte to partake in the "format range" option properly, and so when your editor does auto-format on code action, it will likely invoke prettier with the range option, resulting in the given gibberish.

**Closed by dummdidumm** 2024-01-29 10:30 UTC
