### ISSUE TITLE
svelteSortOrder: "none" completely delete style section.

### ISSUE THREAD

**Issue by KostisFioravantes** [sveltejs/prettier-plugin-svelte#415] opened 2023-12-21 03:33 UTC
I assume this is a bug. I format my project with svelteSortOrder to none and all the <style> sections of my svelte components are erased. I tried to reproduce this behavior and noticed that it happens only to sort orders that end with a <style> section, for example, script-markup-style and markup-script-style orders.

prettier: 3.1.1
prettier-plugin-svelte: 3.1.2

**Comment by KostisFioravantes** [comment] 2023-12-21 03:36
Thats my .prettierrc

{
	"semi": false,
	"tabWidth": 4,
	"useTabs": true,
	"singleQuote": true,
	"arrowParens": "avoid",
	"trailingComma": "es5",
	"plugins": [
		"prettier-plugin-svelte",
		"prettier-plugin-tailwindcss"
	],
	"overrides": [
		{
			"files": "*.svelte",
			"options": {
				"printWidth": 70,
				"parser": "svelte",
				"svelteSortOrder": "none",
				"svelteAllowShorthand": true
			}
		}
	]
}

**Comment by dummdidumm** [comment] 2023-12-21 07:51
Please provide a code snippet that reproduces the issue

**Comment by KostisFioravantes** [comment] 2024-04-22 17:14
It's dup with  #406. Check it for reproduction.

**Comment by dummdidumm** [comment] 2024-04-23 10:05
Closing as duplicate of #406 then

**Closed by dummdidumm** 2024-04-23 10:05 UTC
Labels: needs repro
