### ISSUE TITLE
Add type declarations

### ISSUE THREAD

**Issue by benjaminpreiss** [sveltejs/prettier-plugin-svelte#363] opened 2023-04-29 16:49 UTC
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `prettier-plugin-svelte@2.10.0` for the project I'm working on.

The problem is that there are no types exported... I know this is not a fix, but creating the following path helped me

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/prettier-plugin-svelte/types/index.d.ts b/node_modules/prettier-plugin-svelte/types/index.d.ts
new file mode 100644
index 0000000..30b171d
--- /dev/null
+++ b/node_modules/prettier-plugin-svelte/types/index.d.ts
@@ -0,0 +1,5 @@
+import { SupportLanguage, Parser, Printer } from 'prettier';
+export declare const languages: SupportLanguage[];
+export declare const parsers: Record<string, Parser>;
+export declare const printers: Record<string, Printer>;
+export { options } from './options';
\ No newline at end of file
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by dummdidumm** [comment] 2023-04-29 17:32
Could you give a brief explanation why you need type definitions?

**Comment by DetachHead** [comment] 2023-04-29 21:32
Duplicate of #359

@dummdidumm that issue contains a use case explaining why I need type definitions

**Comment by dummdidumm** [comment] 2023-07-14 09:53
Closing as duplicate of #359

**Closed by dummdidumm** 2023-07-14 09:53 UTC
