### ISSUE TITLE
Prettier plugin svelte does not format typescript code inside `@const` tag

### ISSUE THREAD

**Issue by lts20050703** [sveltejs/prettier-plugin-svelte#442] opened 2024-05-23 06:31 UTC
It looks like Prettier does not format typescript code inside `@const` tag

For example, prettier will successfully format the code below
```svelte
{@const x = a[0]}
```

But it does not format the code below
```svelte
{@const x = a[0] as number}
```

Workaround: None found yet.

**Comment by dummdidumm** [comment] 2024-06-20 13:40
Closing as duplicate of #447

**Closed by dummdidumm** 2024-06-20 13:40 UTC
