### ISSUE TITLE
Inconsistent quote format

### ISSUE THREAD

**Issue by pushkine** [sveltejs/prettier-plugin-svelte#189] opened 2021-01-11 09:31 UTC
input :
```svelte
<script lang="ts">
     const bar = "foo";
</script>

<div use:action={"foo"} />
```
output :
```svelte
<script lang="ts">
	const bar = "foo";
</script>

<div use:action={'foo'} />
```

**Comment by dummdidumm** [comment] 2021-01-11 09:48
Duplicate of #94, fixed since `2.0.0`. You likely don't see this change yet because the VS Code extension comes prepackaged with a pre-`2.x` version. Will update that one soon.

**Closed by dummdidumm** 2021-01-11 09:48 UTC
