### ISSUE TITLE
eslint-disable-line comment is removed inside arrow functions

### ISSUE THREAD

**Issue by openjck** [sveltejs/prettier-plugin-svelte#104] opened 2020-06-26 03:22 UTC
When the following code is run through *prettier-plugin-svelte*, the `// eslint-disable-line` comment is removed:

```svelte
<button on:click={() => {
   acc = acc - 10; // eslint-disable-line
}}>click</button>
```

**Comment by ehrencrona** [comment] 2020-09-03 13:37
This is a duplicate of #96

**Closed** 2020-09-03 13:39 UTC
