### ISSUE TITLE
Automatically lowercasing components in HTML

### ISSUE THREAD

**Issue by nathancahill** [sveltejs/prettier-plugin-svelte#166] opened 2020-12-05 13:32 UTC
Given code like this:

```html
<Form></Form>
```
where `Form` is a Svelte component, prettier-plugin-svelte outputs:

```html
<form></form>
```

This happens when any Svelte component name matches a HTML tag.

**Comment by dummdidumm** [comment] 2020-12-05 15:55
I am not able to reproduce this. Are you using the latest version? Do you have a `.prettierrc` config, and if so, what's in it? Do you format through the Svelte for VS Code extension or through the prettier cli?

**Comment by dummdidumm** [comment] 2021-02-08 09:39
Closing due to lack of reproduction.

**Closed by dummdidumm** 2021-02-08 09:39 UTC
