### ISSUE TITLE
Unterminated HTML tags cause prettier to output nothing, which blanks the buffer in Vim

### ISSUE THREAD

**Issue by groovy9** [sveltejs/prettier-plugin-svelte#107] opened 2020-07-02 23:19 UTC
Prettierrc:

`
{
  "tabWidth": 2,
  "semi": false,
  "singleQuote": true,
  "plugins": ["prettier-plugin-svelte"]
}
`

Source file: 
`<tabl <p>hello, world</p>`

Prettier output:
`src/foo.svelte[error] Cannot read property 'line' of undefined`

This is a bit of a show-stopper.  Prettier should output unchanged file contents if it can't format it.

**Comment by dummdidumm** [comment] 2020-09-03 07:58
Is this still the case? We changed some console logs from log to error to not write to stdout.

**Comment by ehrencrona** [comment] 2020-09-03 13:36
The `Cannot read property 'line' of undefined` will go away due to #132 and be replaced by 

```
src/Broken.svelte[error] src/Broken.svelte: </p> attempted to close an element that was not open
[error] > 1 | <tabl <p>hello, world</p>
[error]     |                     ^ (1:21)
[error] 1: <tabl <p>hello, world</p>
```

However, I have no idea what the Vim integration does with that output :)

**Comment by dummdidumm** [comment] 2021-01-03 13:46
Closing console writes are to the error output and since #132 made the errors compatible with how prettier treats them. If there's still something wrong, please describe in more detail what the problem is and how to reproduce it.

**Closed by dummdidumm** 2021-01-03 13:46 UTC
