### ISSUE TITLE
Infinite printWidth in markup

### ISSUE THREAD

**Issue by pushkine** [sveltejs/prettier-plugin-svelte#190] opened 2021-01-11 09:36 UTC
Input :
```svelte
<div class={"WWWWWWWWWWWWWWWWWW" + "WWWWWWWWWWWWWWWWWW" + "WWWWWWWWWWWWWWWWWW" + "WWWWWWWWWWWWWWWWWW" + "WWWWWWWWWWWWWWWWWW" + "WWWWWWWWWWWWWWWWWW" + "WWWWWWWWWWWWWWWWWW" + "WWWWWWWWWWWWWWWWWW" + "WWWWWWWWWWWWWWWWWW"} />
```
Output :
```svelte
<div
	class={'WWWWWWWWWWWWWWWWWW' + 'WWWWWWWWWWWWWWWWWW' + 'WWWWWWWWWWWWWWWWWW' + 'WWWWWWWWWWWWWWWWWW' + 'WWWWWWWWWWWWWWWWWW' + 'WWWWWWWWWWWWWWWWWW' + 'WWWWWWWWWWWWWWWWWW' + 'WWWWWWWWWWWWWWWWWW' + 'WWWWWWWWWWWWWWWWWW'} />
```
Expected (taken from formatting tsx) :
```svelte
<div
	class={
		"WWWWWWWWWWWWWWWWWW" +
		"WWWWWWWWWWWWWWWWWW" +
		"WWWWWWWWWWWWWWWWWW" +
		"WWWWWWWWWWWWWWWWWW" +
		"WWWWWWWWWWWWWWWWWW" +
		"WWWWWWWWWWWWWWWWWW" +
		"WWWWWWWWWWWWWWWWWW" +
		"WWWWWWWWWWWWWWWWWW" +
		"WWWWWWWWWWWWWWWWWW"
	}
/>
```

**Comment by dummdidumm** [comment] 2021-01-11 09:49
Duplicate of #170, fixed since 2.0.0. You likely don't see this change yet because the VS Code extension comes prepackaged with a pre-2.x version. Will update that one soon.

**Closed by dummdidumm** 2021-01-11 09:49 UTC
