### ISSUE TITLE
prettier --write removed whitespace it wasn't supposed to

### ISSUE THREAD

**Issue by artesgo** [sveltejs/prettier-plugin-svelte#157] opened 2020-10-14 03:12 UTC
![snip](https://user-images.githubusercontent.com/2791900/95938850-c1aded00-0da8-11eb-807c-32d0db4e48b9.PNG)
fig 1: me adding the whitespace back

it appears to be doing so after parsing the file and finding a comment in the
{#if} block

```
{#if someConditional}
  some template
  <!-- may need to be
  a multi-line comment -->
{/if}

<style lang="postcss">
  ...
</style>
```

**Comment by dummdidumm** [comment] 2020-10-14 07:03
Duplicate of #146

**Closed by dummdidumm** 2020-10-14 07:03 UTC
