### ISSUE TITLE
Misformatted Snippet when using a typed instance of a Class

### ISSUE THREAD

**Issue by oliie** [sveltejs/prettier-plugin-svelte#463] opened 2024-09-19 12:51 UTC
My relevant packages:
```json
{
  "@sveltejs/kit": "^2.3.2"
  "svelte": "5.0.0-next.246",
  "prettier": "^3.3.3",
  "prettier-plugin-svelte": "^3.2.6",
}
```

When I have made a `Snippet` with typed arguments using an instance of a Class, the formatting fails and breaks the code.

Example before format:
```html
{#snippet priceListItemsTabContent(title: string, tableInstance: InstanceType<new () => TableHandler<PriceListItem, PriceListItem>>, entityStatus: string)}
```

After format:
```html
{#snippet priceListItemsTabContent(title: string, tableInstance: InstanceType<new ()}
```

This causes the code after to break. I've also noticed it sometimes created duplicated rows of code, but I cant provide an example for that.

I could solve it however by adding line breaks OR extracting the type to the script, causing the formatting to be fine.

Example 1 solution
```html
{#snippet priceListItemsTabContent(
  title: string,
  tableInstance: InstanceType<new () => TableHandler<PriceListItem, PriceListItem>>,
  entityStatus: string
)}
```

Example 2 solution
```html
<script lang="ts">
  type TableHandlerPriceListItem = InstanceType<new () => TableHandler<PriceListItem, PriceListItem>>;
  // ...
</script>

{#snippet priceListItemsTabContent(
    title: string,
    tableInstance: TableHandlerPriceListItem,
    entityStatus: string
)}

<!-- or as one line -->

{#snippet priceListItemsTabContent(title: string, tableInstance: TableHandlerPriceListItem, entityStatus: string)}
```

**Comment by dummdidumm** [comment] 2024-09-26 10:50
Closing as duplicate of #455 (fixed, was released just now)

**Closed by dummdidumm** 2024-09-26 10:50 UTC
